config/routes.rb
Loonwerker::Application.routes.draw do
  resources :reviews, :except => [:show, :new]
  resources :pictures

  get "over-ons", :to => "about#index", :as => "about"

  get "contact", :to => "contact#index"
  post "contact/send-contact", :to => "contact#send_contact", :as => "send_contact"

  get "losse-verhuur", :to => "verhuur#index", :as => "verhuur"

  get "diensten/grondwerk"
  get "diensten/bestraten"
  get "diensten/tuinaanleg"
  get "diensten/slopen"

	get "pictures/move_up"
	get "pictures/move_down"

  devise_for :admins
  devise_scope :admin do
		get "login", :to => "devise/sessions#new"
		get "logout", :to=> "devise/sessions#destroy"
  end

	namespace 'admin' do
		resources :pages, :only => [:index, :edit, :update]
	end 

  root :to => "home#index"

end

app/views/admin/pages/edit.html.erb
<h2>Bewerk de <%= @page.key.titleize %> pagina</h2>
<%= link_to "Terug", admin_pages_path %><br>
<%= form_for @page, :url => admin_page_path(@page), :method => :put do |form| %>
  <%= form.hidden_field :key, :disabled => true %>
  <%= form.hidden_field :locale, :disabled => true %><br><hr>

  <% unless form.object.page_contents.empty? %>
    <% eligible_contents = ManageableContent::Manager.eligible_contents(form.object.key) %>
    <%= form.fields_for :page_contents do |content_form| %>
      <% if eligible_contents.include?(content_form.object.key.to_sym) %>
        <%= content_form.label :content, content_form.object.key %><br>
       	<%= content_form.text_area :content, :class => "wymeditor" %><br><hr>
      <% end %>
    <% end %>
  <% end %>

  <%= form.submit 'Opslaan', :class => "wymupdate" %>
<% end %>
<br><%= link_to "Terug", admin_pages_path %>

app/views/admin/pages/index.html.erb
<h2>Alle pagina's</h2>
<table>
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.key.titleize %></td>
      <td><%= link_to 'edit', edit_admin_page_path(page) %></td>
    </tr>
  <% end %>
</table>