config/routes.rb
Loonwerker::Application.routes.draw do
  resources :reviews, :except => [:show, :new]
  resources :pictures

  get "over-ons", :to => "about#index", :as => "about"

  get "contact", :to => "contact#index"
  post "contact/send-contact", :to => "contact#send_contact", :as => "send_contact"

  get "losse-verhuur", :to => "verhuur#index", :as => "verhuur"

  get "diensten/grondwerk"
  get "diensten/bestraten"
  get "diensten/tuinaanleg"
  get "diensten/slopen"

	get "pictures/move_up"
	get "pictures/move_down"

  devise_for :admins
  devise_scope :admin do
		get "login", :to => "devise/sessions#new"
		get "logout", :to=> "devise/sessions#destroy"
  end

	namespace 'admin' do
		resources :pages, :only => [:index, :edit, :update]
	end 

  root :to => "home#index"

end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>De Kleine Loonwerker | Admin</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
	<script type="text/javascript" src="/wymeditor/jquery.wymeditor.pack.js"></script>
	<script type="text/javascript">
		jQuery(function() {
	    	jQuery(".wymeditor").wymeditor({
	    		jQueryPath: "/assets/application.js",
				stylesheet: "/wymeditor/wymcss.css"
	    	});
		});
	</script>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="main-background">
		<div class="container">
			<div id="notice">
				<% flash.each do |key, value| %>
  				<%= content_tag(:div, value, :class => "site-flash #{key}") %>
				<% end %>
			</div>
			<% if admin_signed_in? %>
				<div id="admin-box">
					<%= link_to "Pagina's beheren", admin_pages_path %><br>
					<%= link_to "Slideshows beheren", pictures_path %><br>
					<%= link_to "Referenties beheren", reviews_path %><br>
					<%= link_to "Logout", logout_path %>
				</div>
			<% end %>
			<header id="header" class="span-24">
				<h1>De Kleine Loonwerker</h1>
				<nav id="main-navigation" class="align-right">
					<%= link_to "Home", root_path, :class => controller_active?('home') %>
					<%= link_to "Diensten", diensten_grondwerk_path, :class => controller_active?('diensten') %>
					<%= link_to "Verhuur", verhuur_path, :class => controller_active?('verhuur') %>
					<%= link_to "Over ons", about_path, :class => controller_active?('about') %>
					<%= link_to "Contact", contact_path, :class => controller_active?('contact') %>
				</nav>
			</header>
			<div class="content-background span-24">
				<%= yield %>
			</div>
		</div>
	</div>
	<div id="footer-outer">
		<footer id="footer">
			<div class="container">
				<div class="span-24 footer-main">
					<div class="align-right">
						<p>De Kleine Loonwerker<br>
						Luuk den Teuling<br>
						Sint Lambertusweg 50<br>
						5291AC, Gemonde<br>
						Tel: 06 10 352 382<br>
						Tel: 073 55 15 552<br>
						Mail: luuk@den-teuling.nl</p>
					</div>
				</div>
			</div>
		</footer>
	</div>
</body>
</html>