config/routes.rb
Loonwerker::Application.routes.draw do
  resources :reviews, :except => [:show, :new]
  resources :pictures

  get "over-ons", :to => "about#index", :as => "about"

  get "contact", :to => "contact#index"
  post "contact/send-contact", :to => "contact#send_contact", :as => "send_contact"

  get "losse-verhuur", :to => "verhuur#index", :as => "verhuur"

  get "diensten/grondwerk"
  get "diensten/bestraten"
  get "diensten/tuinaanleg"
  get "diensten/slopen"

	get "pictures/move_up"
	get "pictures/move_down"

  devise_for :admins
  devise_scope :admin do
		get "login", :to => "devise/sessions#new"
		get "logout", :to=> "devise/sessions#destroy"
  end

	namespace 'admin' do
		resources :pages, :only => [:index, :edit, :update]
	end 

  root :to => "home#index"

end

app/controllers/diensten_controller.rb
class DienstenController < ApplicationController
	manageable_content_for :grondwerk, :bestraten, :tuinaanleg, :slopen, :korte_samenvatting

  def grondwerk
		@pictures = Picture.where(:category => "grondwerk").order("position")
  end

  def bestraten
		@pictures = Picture.where(:category => "bestraten").order("position")
  end

  def tuinaanleg
		@pictures = Picture.where(:category => "tuinaanleg").order("position")
  end

  def slopen
		@pictures = Picture.where(:category => "slopen").order("position")
  end
end

app/helpers/diensten_helper.rb
module DienstenHelper
	def action_active?(action)
		if request.path_parameters[:action] == action
			true
		else
			false
		end
	end

	def get_category
		request.path_parameters[:action]
	end
end

app/views/diensten/_admin_actions.html.erb
<div class="span-24">
	<%= link_to "Foto toevoegen", new_picture_path, :category => get_category %> | 
	<%= link_to "Slideshow bewerken", pictures_path %>
</div>

app/views/diensten/_slider.html.erb
<div id="gallery-wrap">
	<ul id="gallery">
		<% @pictures.each do |picture| %>
				<li class="picture"><%= link_to image_tag(picture.photo.slide), picture_path(picture), :class => "fancybox" %></li>
		<% end %>
	</ul>
</div>
<div id="gallery-controls">
  <%= link_to '< Terug', {}, :id => "gallery-prev" %>
	<%= link_to 'Verder >', {}, :id => "gallery-next" %>
</div>

app/views/diensten/_sub_menu.html.erb
<div class="span-24 header-image rounded-top-corners">
	<div class="diensten-header rounded-top-corners"></div>
</div>
<nav id="sub-navigation" class="prepend-1 span-23 last">
	<%= link_to "Grondwerk", diensten_grondwerk_path, :class => action_active?('grondwerk') %>
	<%= link_to "Bestraten", diensten_bestraten_path, :class => action_active?('bestraten') %>
	<%= link_to "Tuinaanleg", diensten_tuinaanleg_path, :class => action_active?('tuinaanleg') %>
	<%= link_to "Slopen", diensten_slopen_path, :class => action_active?('slopen') %>
</nav>

app/views/diensten/bestraten.html.erb
<% content_for :title do %>
	 | Bestraten en leveren van stenen 
<% end %>

<%= render "sub_menu" %>

<div class="prepend-3 span-18 append-3 last spacer-top-bottom">
	<%= manageable_layout_content_for :bestraten %>
</div>

<%= render 'slider' %>

<% if admin_signed_in? %>
	<%= render 'admin_actions' %>
<% end %>

app/views/diensten/grondwerk.html.erb
<% content_for :title do %>
	 | Afgraven, riolering aanleggen en containerverhuur
<% end %>

<%= render "sub_menu" %>

<div class="prepend-3 span-18 append-3 last spacer-top-bottom">
	<%= manageable_layout_content_for :grondwerk %>
</div>

<%= render 'slider' %>

<% if admin_signed_in? %>
	<%= render 'admin_actions' %>
<% end %>

app/views/diensten/slopen.html.erb
<% content_for :title do %>
	 | Slopen van muren, vloeren en funderingen
<% end %>

<%= render "sub_menu" %>

<div class="prepend-3 span-18 append-3 last spacer-top-bottom">
	<%= manageable_layout_content_for :slopen %>
</div>

<%= render 'slider' %>

<% if admin_signed_in? %>
	<%= render 'admin_actions' %>
<% end %>

app/views/diensten/tuinaanleg.html.erb
<% content_for :title do %>
	 | Aanleggen van tuinen en plaatsen van graszoden
<% end %>

<%= render "sub_menu" %>

<div class="prepend-3 span-18 append-3 last spacer-top-bottom">
	<%= manageable_layout_content_for :tuinaanleg %>
</div>

<%= render 'slider' %>

<% if admin_signed_in? %>
	<%= render 'admin_actions' %>
<% end %>