config/routes.rb
Loonwerker::Application.routes.draw do
  resources :reviews, :except => [:show, :new]
  resources :pictures

  get "over-ons", :to => "about#index", :as => "about"

  get "contact", :to => "contact#index"
  post "contact/send-contact", :to => "contact#send_contact", :as => "send_contact"

  get "losse-verhuur", :to => "verhuur#index", :as => "verhuur"

  get "diensten/grondwerk"
  get "diensten/bestraten"
  get "diensten/tuinaanleg"
  get "diensten/slopen"

	get "pictures/move_up"
	get "pictures/move_down"

  devise_for :admins
  devise_scope :admin do
		get "login", :to => "devise/sessions#new"
		get "logout", :to=> "devise/sessions#destroy"
  end

	namespace 'admin' do
		resources :pages, :only => [:index, :edit, :update]
	end 

  root :to => "home#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	attr_accessible :photo, :category, :position
	validates_presence_of :photo, :category
	before_save :set_position, :only => [:create]
  mount_uploader :photo, PictureUploader

	def set_position
		last_picture = Picture.where(:category => self.category).order("position").last
		if last_picture.nil?
			self.position = 1
		else
			self.position = last_picture.position + 1
		end
	end

	protected

	def move_up
		first_position = Picture.where(:category => self.category).order("position").first.position
		if self.position > first_position
			mem = self.position
			previous_picture = self.previous_picture
			self.update_attribute(:position, previous_picture.position)
			previous_picture.update_attribute(:position, mem)
		end
	end

	def move_down
		last_position = Picture.where(:category => self.category).order("position").last.position
		if self.position < last_position
			mem = self.position
			next_picture = self.next_picture
			self.update_attribute(:position, next_picture.position)
			next_picture.update_attribute(:position, mem)
		end
	end

	def previous_picture
	  Picture.order("position").last(:conditions => ["position < ? and category = ?", self.position, self.category])
	end

	def next_picture
	  Picture.order("position").first(:conditions => ["position > ? and category = ?", self.position, self.category])
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_filter :authenticate_admin!, :except => [:show] 

  # GET /pictures
  # GET /pictures.json
	def move_up
		picture = Picture.find(params[:picture])
		picture.move_up
		redirect_to pictures_path
	end

	def move_down
		picture = Picture.find(params[:picture])
		picture.move_down
		redirect_to pictures_path
	end

  def index
    @grondwerk_pictures = Picture.where(:category => "grondwerk").order("position")
		@bestraten_pictures = Picture.where(:category => "bestraten").order("position")
		@tuinaanleg_pictures = Picture.where(:category => "tuinaanleg").order("position")
		@slopen_pictures = Picture.where(:category => "slopen").order("position")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

	def show
		@picture = Picture.find(params[:id])
		render :layout => false
	end
  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    if @picture.save
      redirect_to pictures_path, notice: 'Foto is succesvol toegevoegd'
    else
      render action: "new"
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(params[:picture])
      redirect_to pictures_path, notice: 'Foto is succesvol bewerkt'
    else
      render action: "edit"
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :ok }
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
 		<%= f.select(:category, ["grondwerk", "bestraten", "tuinaanleg", "slopen"], :selected => params[:category]) %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h2>Foto bewerken</h2>

<%= render 'form' %>

<%= link_to 'Terug', pictures_path %>

app/views/pictures/index.html.erb
<h2>Slidewhows beheren</h2>

<h3>Grondwerk</h3>
<table>
	<% @grondwerk_pictures.each do |picture| %>
	  <tr>
	    <td><%= image_tag(picture.photo.thumb) %></td>
	    <td><%= link_to 'Bewerken', edit_picture_path(picture) %></td>
	    <td><%= link_to 'Verwijderen', picture, confirm: 'Weet je het zeker?', method: :delete %></td>
			<td><%= link_to 'Naar voren', :controller => 'pictures', :action => "move_up", :picture => picture %></td>
			<td><%= link_to 'Naar achteren', :controller => 'pictures', :action => "move_down", :picture => picture %></td>
	  </tr>
	<% end %>
</table>
<%= link_to 'Foto toevoegen', :controller => :pictures, :action => :new, :category => "grondwerk" %>

<br><br>

<h3>Bestraten</h3>
<table>
	<% @bestraten_pictures.each do |picture| %>
	  <tr>
	    <td><%= image_tag(picture.photo.thumb) %></td>
	    <td><%= link_to 'Bewerken', edit_picture_path(picture) %></td>
	    <td><%= link_to 'Verwijderen', picture, confirm: 'Weet je het zeker?', method: :delete %></td>
			<td><%= link_to 'Naar voren', :controller => 'pictures', :action => "move_up", :picture => picture %></td>
			<td><%= link_to 'Naar achteren', :controller => 'pictures', :action => "move_down", :picture => picture %></td>
	  </tr>
	<% end %>
</table>
<%= link_to 'Foto toevoegen', :controller => :pictures, :action => :new, :category => "bestraten" %>

<br><br>

<h3>Tuinaanleg</h3>
<table>
	<% @tuinaanleg_pictures.each do |picture| %>
	  <tr>
	    <td><%= image_tag(picture.photo.thumb) %></td>
	    <td><%= link_to 'Bewerken', edit_picture_path(picture) %></td>
	    <td><%= link_to 'Verwijderen', picture, confirm: 'Weet je het zeker?', method: :delete %></td>
			<td><%= link_to 'Naar voren', :controller => 'pictures', :action => "move_up", :picture => picture %></td>
			<td><%= link_to 'Naar achteren', :controller => 'pictures', :action => "move_down", :picture => picture %></td>
	  </tr>
	<% end %>
</table>
<%= link_to 'Foto toevoegen', :controller => :pictures, :action => :new, :category => "tuinaanleg" %>

<br><br>

<h3>Slopen</h3>
<table>
	<% @slopen_pictures.each do |picture| %>
	  <tr>
	    <td><%= image_tag(picture.photo.thumb) %></td>
	    <td><%= link_to 'Bewerken', edit_picture_path(picture) %></td>
	    <td><%= link_to 'Verwijderen', picture, confirm: 'Weet je het zeker?', method: :delete %></td>
			<td><%= link_to 'Naar voren', :controller => 'pictures', :action => "move_up", :picture => picture %></td>
			<td><%= link_to 'Naar achteren', :controller => 'pictures', :action => "move_down", :picture => picture %></td>
	  </tr>
	<% end %>
</table>
<%= link_to 'Foto toevoegen', :controller => :pictures, :action => :new, :category => "slopen" %>

app/views/pictures/new.html.erb
<h2>Foto toevoegen</h2>

<%= render 'form' %>

<%= link_to 'Terug', pictures_path %>

app/views/pictures/show.html.erb
<div class="picture-show">
	<%= image_tag @picture.photo %>
</div>